movies = [
    {"title": "Inception", "genre": ["Sci-Fi", "Action"], "rating": 8.8},
    {"title": "Interstellar", "genre": ["Sci-Fi", "Adventure"], "rating": 8.7},
    {"title": "The Dark Knight", "genre": ["Action", "Crime"], "rating": 9.0},
    {"title": "Batman Begins", "genre": ["Action", "Crime"], "rating": 8.2},
    {"title": "The Dark Knight Rises", "genre": ["Action"], "rating": 8.4},
    {"title": "Avengers: Endgame", "genre": ["Action", "Adventure"], "rating": 8.4},
    {"title": "Avengers: Infinity War", "genre": ["Action", "Adventure"], "rating": 8.4},
    {"title": "Iron Man", "genre": ["Action", "Sci-Fi"], "rating": 7.9},
    {"title": "Captain America: Civil War", "genre": ["Action"], "rating": 7.8},
    {"title": "Doctor Strange", "genre": ["Fantasy", "Action"], "rating": 7.5},
    {"title": "Spider-Man: No Way Home", "genre": ["Action", "Adventure"], "rating": 8.2},
    {"title": "Black Panther", "genre": ["Action"], "rating": 7.3},
    {"title": "Thor: Ragnarok", "genre": ["Action", "Comedy"], "rating": 7.9},
    {"title": "Guardians of the Galaxy", "genre": ["Sci-Fi", "Comedy"], "rating": 8.0},
    {"title": "The Matrix", "genre": ["Sci-Fi", "Action"], "rating": 8.7},
    {"title": "The Matrix Reloaded", "genre": ["Sci-Fi"], "rating": 7.2},
    {"title": "The Matrix Revolutions", "genre": ["Sci-Fi"], "rating": 6.8},
    {"title": "Titanic", "genre": ["Romance", "Drama"], "rating": 7.9},
    {"title": "The Notebook", "genre": ["Romance", "Drama"], "rating": 7.8},
    {"title": "La La Land", "genre": ["Romance", "Drama"], "rating": 8.0},
    {"title": "A Star Is Born", "genre": ["Romance", "Drama"], "rating": 7.6},
    {"title": "3 Idiots", "genre": ["Comedy", "Drama"], "rating": 8.4},
    {"title": "PK", "genre": ["Comedy", "Drama"], "rating": 8.1},
    {"title": "Dangal", "genre": ["Drama", "Sport"], "rating": 8.3},
    {"title": "Lagaan", "genre": ["Drama", "Sport"], "rating": 8.1},
    {"title": "Bahubali: The Beginning", "genre": ["Action", "Fantasy"], "rating": 8.0},
    {"title": "Bahubali 2", "genre": ["Action", "Fantasy"], "rating": 8.2},
    {"title": "KGF Chapter 1", "genre": ["Action"], "rating": 8.2},
    {"title": "KGF Chapter 2", "genre": ["Action"], "rating": 8.2},
    {"title": "RRR", "genre": ["Action", "Drama"], "rating": 7.8},
    {"title": "Pushpa", "genre": ["Action"], "rating": 7.6},
    {"title": "Salaar", "genre": ["Action"], "rating": 6.8},
    {"title": "Leo", "genre": ["Action", "Thriller"], "rating": 7.2},
    {"title": "Jailer", "genre": ["Action"], "rating": 7.1},
    {"title": "Vikram", "genre": ["Action", "Thriller"], "rating": 8.3},
    {"title": "Master", "genre": ["Action"], "rating": 7.3},
    {"title": "The Conjuring", "genre": ["Horror"], "rating": 7.5},
    {"title": "The Conjuring 2", "genre": ["Horror"], "rating": 7.3},
    {"title": "Annabelle", "genre": ["Horror"], "rating": 5.5},
    {"title": "Insidious", "genre": ["Horror"], "rating": 6.8},
    {"title": "IT", "genre": ["Horror"], "rating": 7.3},
    {"title": "The Nun", "genre": ["Horror"], "rating": 5.3},
    {"title": "Smile", "genre": ["Horror"], "rating": 6.5},
    {"title": "Get Out", "genre": ["Horror", "Thriller"], "rating": 7.8},
    {"title": "Us", "genre": ["Horror"], "rating": 6.8},
    {"title": "Coco", "genre": ["Animation", "Family"], "rating": 8.4},
    {"title": "Frozen", "genre": ["Animation", "Family"], "rating": 7.5},
    {"title": "Frozen II", "genre": ["Animation"], "rating": 6.8},
    {"title": "Toy Story", "genre": ["Animation", "Family"], "rating": 8.3},
    {"title": "Toy Story 2", "genre": ["Animation"], "rating": 7.9},
    {"title": "Toy Story 3", "genre": ["Animation"], "rating": 8.3},
    {"title": "Finding Nemo", "genre": ["Animation"], "rating": 8.2},
    {"title": "Finding Dory", "genre": ["Animation"], "rating": 7.3},
    {"title": "Cars", "genre": ["Animation"], "rating": 7.2},
    {"title": "Inside Out", "genre": ["Animation"], "rating": 8.1},
    {"title": "Moana", "genre": ["Animation"], "rating": 7.6},
    {"title": "Zootopia", "genre": ["Animation"], "rating": 8.0},
    {"title": "The Lion King", "genre": ["Animation", "Adventure"], "rating": 8.5},
    {"title": "Aladdin", "genre": ["Animation", "Fantasy"], "rating": 8.0},
    {"title": "Shrek", "genre": ["Animation", "Comedy"], "rating": 7.9},
    {"title": "Kung Fu Panda", "genre": ["Animation", "Comedy"], "rating": 7.6},
    {"title": "Kung Fu Panda 2", "genre": ["Animation"], "rating": 7.2},
    {"title": "How to Train Your Dragon", "genre": ["Animation"], "rating": 8.1},
    {"title": "Minions", "genre": ["Animation", "Comedy"], "rating": 6.4},
    {"title": "Despicable Me", "genre": ["Animation", "Comedy"], "rating": 7.6},
    {"title": "The Godfather", "genre": ["Crime", "Drama"], "rating": 9.2},
    {"title": "The Godfather Part II", "genre": ["Crime", "Drama"], "rating": 9.0},
    {"title": "Pulp Fiction", "genre": ["Crime"], "rating": 8.9},
    {"title": "Fight Club", "genre": ["Drama"], "rating": 8.8},
    {"title": "Forrest Gump", "genre": ["Drama"], "rating": 8.8},
    {"title": "The Shawshank Redemption", "genre": ["Drama"], "rating": 9.3},
    {"title": "The Green Mile", "genre": ["Drama"], "rating": 8.6},
    {"title": "Gladiator", "genre": ["Action", "Drama"], "rating": 8.5},
    {"title": "Braveheart", "genre": ["Action", "Drama"], "rating": 8.3},
    {"title": "Mad Max: Fury Road", "genre": ["Action"], "rating": 8.1},
    {"title": "John Wick", "genre": ["Action"], "rating": 7.4},
    {"title": "John Wick: Chapter 2", "genre": ["Action"], "rating": 7.4},
    {"title": "John Wick: Chapter 3", "genre": ["Action"], "rating": 7.9},
    {"title": "Top Gun: Maverick", "genre": ["Action"], "rating": 8.2},
    {"title": "Mission: Impossible - Fallout", "genre": ["Action"], "rating": 7.7},
    {"title": "Skyfall", "genre": ["Action"], "rating": 7.8},
    {"title": "Casino Royale", "genre": ["Action"], "rating": 8.0},
    {"title": "No Time to Die", "genre": ["Action"], "rating": 7.3},
    {"title": "The Prestige", "genre": ["Drama", "Mystery"], "rating": 8.5},
    {"title": "Memento", "genre": ["Mystery", "Thriller"], "rating": 8.4},
    {"title": "Se7en", "genre": ["Crime", "Thriller"], "rating": 8.6},
    {"title": "Gone Girl", "genre": ["Thriller"], "rating": 8.1},
    {"title": "Shutter Island", "genre": ["Thriller"], "rating": 8.2},
    {"title": "Prisoners", "genre": ["Thriller"], "rating": 8.2},
    {"title": "The Silence of the Lambs", "genre": ["Thriller"], "rating": 8.6},
    {"title": "Whiplash", "genre": ["Drama"], "rating": 8.5},
    {"title": "The Social Network", "genre": ["Drama"], "rating": 7.8},
    {"title": "Joker", "genre": ["Crime", "Drama"], "rating": 8.4},
    {"title": "Oppenheimer", "genre": ["Drama"], "rating": 8.3},
    {"title": "Barbie", "genre": ["Comedy"], "rating": 6.9},
    {"title": "The Super Mario Bros. Movie", "genre": ["Animation"], "rating": 7.0},
    {"title": "Elemental", "genre": ["Animation"], "rating": 7.0},
    {"title": "Soul", "genre": ["Animation"], "rating": 8.0},
    {"title": "Encanto", "genre": ["Animation"], "rating": 7.2},
    {"title": "The Incredibles", "genre": ["Animation", "Action"], "rating": 8.0},
    {"title": "Big Hero 6", "genre": ["Animation", "Action"], "rating": 7.8},
]